// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDllfVhTP2Ng3n2Xct0YwUwr4cRn3SE7wU',
    appId: '1:548693770600:web:3991bc66ebeb249ec1d6dd',
    messagingSenderId: '548693770600',
    projectId: 'kecap-7b158',
    authDomain: 'kecap-7b158.firebaseapp.com',
    storageBucket: 'kecap-7b158.firebasestorage.app',
    measurementId: 'G-1RV6ZTCW3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt6Exlo8f9KvHJDrelxsKeIpkmIUShDio',
    appId: '1:77343845012:android:0e5ec228a4771c4ac42281',
    messagingSenderId: '77343845012',
    projectId: 'mobile-modul-6-c5e5e',
    storageBucket: 'mobile-modul-6-c5e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDmJM_Kquv3Gn7uCrL1D2GiY7jdbj7OiY',
    appId: '1:77343845012:ios:da4f20cbf1e7f852c42281',
    messagingSenderId: '77343845012',
    projectId: 'mobile-modul-6-c5e5e',
    storageBucket: 'mobile-modul-6-c5e5e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

}